const express = require('express');
const cors = require('cors');
const app = express();
const PORT = 4222;

app.use(cors());
app.use(express.json());

let currentVersion = 'v1.0.0';
let releaseNotes = 'Initial version release.';
let lastUpdateTime = new Date().toISOString();

// Trigger a mock new release version every 5 minutes (300,000 ms)
const UPDATE_INTERVAL_MS = 5 * 60 * 1000;
let versionCounter = 0;

setInterval(() => {
  versionCounter++;
  currentVersion = `v1.0.${versionCounter}`;
  releaseNotes = `Automatic scheduled update release ${currentVersion} generated by background updater.`;
  lastUpdateTime = new Date().toISOString();
  console.log(`[Scheduler] 🆕 New server application update released: ${currentVersion} at ${lastUpdateTime}`);
}, UPDATE_INTERVAL_MS);

// API Endpoint to check for updates
app.get('/api/check-update', (req, res) => {
  const clientVersion = req.query.current_version || 'v1.0.0';
  const hasUpdate = clientVersion !== currentVersion;
  
  res.json({
    updateAvailable: hasUpdate,
    latestVersion: currentVersion,
    url: `http://localhost:${PORT}/downloads/app-${currentVersion}.zip`,
    releaseNotes: releaseNotes,
    updatedAt: lastUpdateTime
  });
});

// Mock download file endpoint
app.get('/downloads/:filename', (req, res) => {
  const filename = req.params.filename;
  console.log(`[Download] Client requested download: ${filename}`);
  res.send(`Mock binary data stream for ${filename}`);
});

// Status monitor endpoint
app.get('/status', (req, res) => {
  const nextUpdateMs = UPDATE_INTERVAL_MS - (Date.now() % UPDATE_INTERVAL_MS);
  res.json({
    status: 'online',
    port: PORT,
    currentVersion: currentVersion,
    lastUpdateTime: lastUpdateTime,
    nextUpdateInSeconds: Math.round(nextUpdateMs / 1000)
  });
});

app.listen(PORT, () => {
  console.log(`🚀 Updater Server running on http://localhost:${PORT}`);
  console.log(`⏰ Scheduled to release new version upgrades every 5 minutes`);
});
